export default [
  ["群核空间智能平台致力于为机器人、AIGC、XR等行业提供优质的数据服务。", "SpatialVerse provides high-quality data services for robotics, AIGC, XR and related industries."],
  ["空间智能解决方案", "Spatial Intelligence Solutions"],
  ["群核空间智能平台面向 AIGC、计算机视觉与机器人行业的数据核心能力。", "SpatialVerse provides core data capabilities for AIGC, computer vision and robotics."],
  ["3D 数据, 核心能力, 群核, 空间智能", "3D Data, Core Competency, Coohom, Spatial Intelligence"],
  ["返回核心能力，继续探索群核的数据基础设施", "Return to Core Competency and explore SpatialVerse data infrastructure"],
  ["把3D数据转化为可被客户理解和体验的产品价值。", "Turn 3D data into product value that customers can understand and experience."],
  ["群核空间智能平台", "Spatial Intelligence Platform"],
  ["AI数据解决方案先行者", "Pioneer in AI Data Solutions"],
  ["首页", "Home"],
  ["解决方案", "Solutions"],
  ["核心能力", "Core Competency"],
  ["学术研究", "Academic Research"],
  ["样例数据集", "Sample Datasets"],
  ["关于我们", "About Us"],
  ["联系我们", "Contact Us"],
  ["中文 / EN", "EN / ZH"],
  ["了解更多", "Learn More"],
  ["免费下载数据集", "Download Dataset"],
  ["开始沟通", "Start a Conversation"],
  ["与我们连接", "Connect With Us"],
  ["返回顶部", "Back to Top"],
  ["返回顶部 ↗", "Back to Top ↗"],
  ["提交", "Submit"],
  ["电子邮件*", "Email*"],
  ["留言", "Message"],
  ["请描述您的需求", "Tell us about your requirements"],
  ["我对以下内容感兴趣：", "I am interested in:"],
  ["感谢提交，我们会尽快联系您。", "Thank you. We will contact you shortly."],
  ["我们会将您的信息添加到我们的客户关系管理，以便与您联系。欲了解更多信息，请联系我们。", "We will add your information to our CRM so we can follow up. For more information, contact us."],
  ["群核空间智能平台 / SPATIALVERSE", "SPATIALVERSE / SPATIAL INTELLIGENCE PLATFORM"],
  ["群核空间智能平台 / AI DATA SOLUTIONS", "SPATIALVERSE / AI DATA SOLUTIONS"],
  ["AI数据解决方案先行者", "Pioneer in AI Data Solutions"],
  ["致力于为机器人、AIGC、XR等行业提供优质的数据服务。我们基于全球领先的室内设计平台，为您提供多样化的室内合成数据，包括图片、3D模型、3D场景等标准数据服务以及个性化定制服务。", "We provide high-quality data services for robotics, AIGC, XR and adjacent industries. Built on a leading interior design platform, we deliver synthetic images, 3D models, 3D scenes and custom data services."],
  ["01 / 解决方案", "01 / SOLUTIONS"],
  ["围绕机器人、AIGC、产品可视化推广与XR等应用场景，提供从数据采集到使用的完整支持。", "We support robotics, AIGC, product visualization and XR from data capture through deployment."],
  ["智能体感知", "Agent Perception"],
  ["机器人仿真", "Robotic Simulation"],
  ["产品可视化推广", "Visualized Product Promotion"],
  ["拓展现实", "Extended Reality"],
  ["感知 / 标注", "Perception / Annotation"],
  ["生成 / 训练", "Generation / Training"],
  ["仿真 / 验证", "Simulation / Validation"],
  ["展示 / 转化", "Visualization / Conversion"],
  ["XR / 交互", "XR / Interaction"],
  ["空间智能数据中枢", "Spatial Intelligence Data Core"],
  ["从真实空间采集、合成到模型训练与应用落地，形成可追踪的AI数据闭环。", "From real-space capture and synthesis to model training and deployment, we build a traceable AI data loop."],
  ["让智能设备看见空间、识别物体并理解环境。", "Help intelligent devices see spaces, recognize objects and understand environments."],
  ["为生成式模型提供图像、视频、模型与完整标签体系。", "Provide images, video, models and complete annotation systems for generative models."],
  ["在高渲染、强物理真实性的环境中完成低成本验证。", "Validate ideas at low cost in high-fidelity, physically realistic environments."],
  ["将3D数据转化为可被客户理解和体验的产品价值。", "Turn 3D data into product value that customers can understand and experience."],
  ["连接AR、VR、MR中的模型、材质与动画，延展数字世界。", "Connect models, materials and animation across AR, VR and MR to extend the digital world."],
  ["02 / 核心能力", "02 / CORE COMPETENCY"],
  ["基于全球领先的室内设计平台，构建面向不同模型、平台和应用场景的数据能力。", "Built on a leading interior design platform, we create data capabilities for different models, platforms and applications."],
  ["物理增强能力", "Physical Enhancement"],
  ["分割标注能力", "Segmentation & Annotation"],
  ["场景增强能力", "Scene Enhancement"],
  ["多通道支持能力", "Multi-channel Support"],
  ["赋予模型密度，摩擦力，弹性，阻尼等真实的物理性质信息，同时还可以对活动部件进行可活动的物理约束", "Add real physical properties such as density, friction, elasticity and damping, with constraints for moving parts."],
  ["自动化结合人工标注技术，可实现包含语义，材质，状态等多种形态信息标注", "Combine automation with human annotation to label semantics, materials, states and other dimensions."],
  ["通过场景设计工具、场景繁化、模型变形、场景光线模拟等能力，使场景数据更多样", "Expand scene variety through scene design, scene variation, model deformation and lighting simulation."],
  ["支持多平台、高效率、更完整的3D模型数据导出，以及3D环境和衍生图片生成能力", "Support efficient multi-platform export of complete 3D model data, plus 3D environments and derived image generation."],
  ["03 / 学术与技术支持", "03 / RESEARCH & TECHNICAL SUPPORT"],
  ["为什么选择我们？", "Why Choose Us?"],
  ["探索更多学术成果", "Explore Research"],
  ["群核科技旗下的Koolab创新实验室借助酷家乐全球最大规模的3D室内设计平台，自2018年起专注于研发3D场景虚拟合成技术。我们与国内外多家高校和科研机构展开深入合作，为群核空间智能平台提供可靠的技术支持，使其能为AIGC、机器人、室内智能体、XR等领域提供创新的虚拟合成数据产品和服务。", "Koolab, the innovation lab of Coohom, has focused on synthetic 3D scene technology since 2018, using Coohom's global interior design platform. We work with universities and research institutions to deliver reliable technology for AIGC, robotics, embodied intelligence and XR."],
  ["品牌企业客户", "Enterprise Customers"],
  ["3D商品素材模型", "3D Product Models"],
  ["AI生成图片", "AI-generated Images"],
  ["合作覆盖国家和地区", "Countries and Regions"],
  ["04 / 服务方式", "04 / SERVICE MODEL"],
  ["支持模式", "Support Models"],
  ["借助群核空间智能平台专业的数据集服务释放定制数据解决方案的力量。我们的团队专注于生成和定制2D和3D数据集，为您提供经济高效、高质量的数据获取服务。", "Our professional dataset services turn custom data requirements into practical solutions. We generate and curate 2D and 3D datasets for efficient, high-quality data acquisition."],
  ["数据解决方案服务", "Data Solution Services"],
  ["定制化数据处理服务", "Custom Data Processing"],
  ["学术研究合作", "Academic Collaboration"],
  ["05 / 联系我们", "05 / CONTACT"],
  ["Our Dataset Products", "Our Dataset Products"],
  ["2D Synthetic Datasets/Videos", "2D Synthetic Datasets/Videos"],
  ["3D Models", "3D Models"],
  ["3D Scenes", "3D Scenes"],
  ["Registration number: 浙ICP备12022366号", "Registration number: Zhejiang ICP 12022366"],
  ["Business License", "Business License"],
  ["我对以下内容感兴趣：", "I am interested in:"],
  ["06 / ABOUT / SPATIAL INTELLIGENCE", "06 / ABOUT / SPATIAL INTELLIGENCE"],
  ["关于我们", "About Us"],
  ["群核空间智能平台致力于把真实空间、数字资产与人工智能连接起来，为机器人、AIGC、室内智能体与 XR 等领域提供可规模化使用的数据能力。", "SpatialVerse connects real space, digital assets and artificial intelligence, delivering scalable data capabilities for robotics, AIGC, embodied indoor agents and XR."],
  ["让空间数据成为智能应用的基础设施", "Make Spatial Data the Infrastructure for Intelligent Applications"],
  ["从场景资产到智能应用", "From Scene Assets to Intelligent Applications"],
  ["持续运行的数据规模", "A Data Platform That Runs at Scale"],
  ["总注册用户", "Registered Users"],
  ["3D 场景", "3D Scenes"],
  ["3D 材质", "3D Materials"],
  ["日渲染图总量", "Daily Rendered Images"],
  ["我们把室内场景、3D 模型、材质、渲染与标注能力组织成可复用的数据基础设施，让研究者和企业能够更快地获得适合训练、仿真、验证与展示的数据产品。", "We organize indoor scenes, 3D models, materials, rendering and annotation into reusable data infrastructure, helping researchers and enterprises access products for training, simulation, validation and presentation."],
  ["让下一组数据进入真实应用。", "Bring the Next Dataset into Real Applications."],
  ["学术合作", "Academic Collaboration"],
  ["学术研究团队在合成数据、AIGC、智能体与室内场景理解方向的研究成果。", "Research across synthetic data, AIGC, intelligent agents and indoor scene understanding."],
  ["样例数据集", "Sample Datasets"],
  ["用于研究项目中 AI 的训练与评估，覆盖 3D 模型、3D 场景与 2D 图像，支持评估阶段免费使用。", "Datasets for AI training and evaluation, covering 3D models, 3D scenes and 2D images, free to use during evaluation."],
  ["数据集资源库", "Dataset Library"],
  ["按数据类型和关键词筛选，打开卡片查看详情并预览下载信息。", "Filter by data type or keyword, then open a card to preview details and download information."],
  ["全部数据", "All Data"],
  ["模型数据", "Model Data"],
  ["场景数据", "Scene Data"],
  ["图像数据", "Image Data"],
  ["搜索数据集名称、标签或格式", "Search dataset names, tags or formats"],
  ["导入图片预览", "Import image preview"],
  ["＋ 导入图片", "+ Import Image"],
  ["没有找到匹配的数据集，请更换关键词或分类。", "No matching datasets. Try another keyword or category."],
  ["数据格式", "Data Format"],
  ["免费获取", "Get for Free"],
  ["场景设计", "Scene Design"],
  ["数据采集", "Data Capture"],
  ["数据标注", "Data Annotation"],
  ["数据安全保障", "Data Security"],
  ["质量与准确性", "Quality & Accuracy"],
  ["成本效率", "Cost Efficiency"],
  ["数据服务流程", "Data Service Workflow"],
  ["智能体数据落地的四个阻力", "Four Barriers to Deploying Agent Data"],
  ["数据获取困难", "Difficult Data Acquisition"],
  ["处理流程繁琐", "Complex Processing"],
  ["数据成本高", "High Data Cost"],
  ["隐私风险", "Privacy Risk"],
  ["让 AI 智能体真正看懂空间。", "Help AI agents truly understand space."],
  ["基于虚拟场景生成合成数据，提升智能设备在真实室内环境中的感知、建图、导航与识别能力。", "Generate synthetic data from virtual scenes to improve intelligent devices' perception, mapping, navigation and recognition in real interiors."],
  ["首页解决方案中的对应视频已同步到本页面，用于展示该方向的数据生成、空间理解与应用状态。", "The corresponding homepage solution video is available here to show data generation, spatial understanding and application status."],
  ["预留视频字段", "Video field reserved"],
  ["从场景到可用数据", "From Scenes to Usable Data"],
  ["模型训练高度依赖合格数据，真实环境采集成本高、周期长，数据质量也难以稳定控制。", "Model training depends on qualified data, while real-world capture is costly, slow and difficult to control for quality."],
  ["原始数据往往不能直接使用，还需要清洗、筛选和标注，消耗大量人力与时间。", "Raw data is rarely ready to use and requires cleaning, filtering and annotation, consuming significant time and effort."],
  ["AI 应用需要海量数据，模型效果与数据投入并非线性增长，规模化采集成为现实压力。", "AI applications need massive datasets, while model quality does not grow linearly with data investment, making scalable capture a real pressure."],
  ["真实采集容易接触个人信息与公共环境数据，数据使用合规需要从源头被考虑。", "Real-world capture can expose personal information and public-space data, so compliance must be considered at the source."],
  ["自动化工具结合人工复核，对不合格数据进行筛选和清洗，确保交付数据可以直接进入训练流程。", "Automation and human review filter and clean invalid data so delivered datasets can enter training workflows directly."],
  ["借助大规模场景库和云端渲染能力，合成数据的整体生产成本显著低于传统真实数据采集。", "Large scene libraries and cloud rendering make synthetic data significantly more cost-efficient than traditional real-world capture."],
  ["从数据源头采取合规措施，生成过程不接触真实敏感信息，满足企业数据使用要求。", "Compliance measures begin at the source; generation avoids real sensitive information and meets enterprise data requirements."],
  ["利用完整的场景设计工具，为住宅、商业、医疗等环境构建定制化室内空间。", "Use a complete scene design toolkit to build customized interiors for residential, commercial and healthcare environments."],
  ["基于 KOOLAI 合成数据采集平台，灵活配置相机参数、运动轨迹和光照效果，模拟真实设备采集。", "Use the KOOLAI synthetic capture platform to configure camera parameters, motion paths and lighting, simulating real device capture."],
  ["通过结构化环境数据生成像素级标签，并结合人工输入提供语义、材质、位置与状态等信息。", "Generate pixel-level labels from structured environment data and add semantic, material, position and state information through human input."],
  ["室内智能设备诸如扫地机器人，家庭看护机器人，室内无人机等，需要面对复杂的室内环境，并具备环境建图，导航规划，物体识别能力，群核空间智能平台旨在通过大规模的室内环境数据，比如带标注的2D图片数据集以及3D环境数据，帮助智能设备厂商以高性价比的方式实现数据采集和使用。", "Indoor intelligent devices such as robot vacuums, home-care robots and indoor drones must navigate complex environments with mapping, planning and object recognition. SpatialVerse uses large-scale indoor data, including annotated 2D images and 3D environments, to help device makers collect and use data cost-effectively."],

  ["为大模型提供多模态训练燃料。", "Multimodal training fuel for foundation models."],
  ["以图像、视频、模型与完整标签体系覆盖生成式大模型的预训练需求，让 AIGC 数据获取更快、更稳、更成体系。", "Cover pre-training needs for generative models with images, video, models and complete labels, making AIGC data acquisition faster, more reliable and more systematic."],
  ["AIGC 数据获取的三重挑战", "Three challenges in AIGC data acquisition"],
  ["数据需求巨大", "Massive data demand"],
  ["模型规模增长带来指数级训练资源需求，数据获取、更新和维护都需要大量成本与时间。", "Growing model scale creates exponential training-resource demand, while data acquisition, updates and maintenance require substantial time and cost."],
  ["标注要求复杂", "Complex annotation requirements"],
  ["AIGC 训练覆盖图像、视频、3D 模型等多种格式，同时需要语义、材质、位置和状态等多维标签。", "AIGC training spans images, video and 3D models, with multidimensional labels for semantics, materials, positions and states."],
  ["隐私与合规", "Privacy and compliance"],
  ["全球数据法规持续收紧，数据来源合规和产品全球化交付成为研究与商业化的基础。", "As data regulations tighten worldwide, compliant sourcing and globally deliverable products become the foundation for research and commercialization."],
  ["一套数据基础设施，多种生成格式", "One data infrastructure, many generation formats"],
  ["完整数据格式", "Complete data formats"],
  ["依托大规模场景数据库和扩展工具，支持图像、视频与 3D 数据的多样化生成和标准化交付。", "Built on large-scale scene databases and extension tools, support diverse generation and standardized delivery of images, video and 3D data."],
  ["完整标注能力", "Complete annotation capability"],
  ["自动化工具与人工标注结合，为训练数据提供覆盖语义、材质、位置与状态的主客观信息。", "Combine automation with human annotation to provide objective and subjective training information across semantics, materials, positions and states."],
  ["数据生成过程不访问真实敏感数据，从源头保护数据使用合规与客户交付安全。", "The generation process does not access real sensitive data, protecting compliant use and delivery security at the source."],
  ["服务能力", "Service capabilities"],
  ["数据专家技术支持", "Data expert support"],
  ["由数据专家梳理技术需求，并结合平台能力设计完整的数据生成与交付方案。", "Data experts clarify technical requirements and design complete generation and delivery plans around platform capabilities."],
  ["定制化数据", "Custom data"],
  ["根据客户模型阶段和研究方向，提供灵活的数据规格、标签体系与分阶段交付计划。", "Provide flexible data specifications, label systems and phased delivery plans based on model maturity and research direction."],
  ["规模化交付", "Scaled delivery"],
  ["通过自研图形渲染引擎与云计算平台，快速交付数十万乃至百万级数据点。", "Use a proprietary graphics rendering engine and cloud platform to quickly deliver hundreds of thousands or millions of data points."],

  ["在数字空间里验证下一代机器人。", "Validate the next generation of robots in digital space."],
  ["连接主流仿真平台，构建兼具高渲染质量与物理真实性的机器人仿真环境，降低真实设备试错成本。", "Connect mainstream simulation platforms to build robot simulation environments with high rendering quality and physical realism, reducing the cost of testing real hardware."],
  ["机器人仿真的三个瓶颈", "Three bottlenecks in robot simulation"],
  ["感知与交互不足", "Insufficient perception and interaction"],
  ["机器人不仅要识别环境，还要理解空间并完成交互，真实世界中的感知能力仍然是关键缺口。", "Robots must not only recognize environments but also understand space and interact with it; real-world perception remains a critical gap."],
  ["实体迭代成本高", "High cost of physical iteration"],
  ["实体机器人开发和迭代周期长、成本高，研发团队需要更快验证多种性能方案。", "Physical robot development and iteration are slow and expensive, so teams need faster ways to validate multiple performance options."],
  ["仿真资源不足", "Insufficient simulation resources"],
  ["现有工具在完整性和数据资源建设上仍有缺口，难以直接支撑规模化仿真训练。", "Existing tools still lack completeness and data resources for directly supporting simulation training at scale."],
  ["从渲染真实性到平台兼容", "From rendering realism to platform compatibility"],
  ["高渲染真实感", "High-fidelity rendering"],
  ["增强 3D 数据的渲染效果，在 UE、Isaac Sim 等环境中尽可能接近真实世界，提升训练泛化能力。", "Enhance 3D rendering to approach the real world in UE, Isaac Sim and similar environments, improving training generalization."],
  ["物理真实性", "Physical realism"],
  ["提供密度、摩擦力、弹性、阻尼等物理参数，并支持抽屉、门等活动部件的物理约束。", "Provide physical parameters such as density, friction, elasticity and damping, with constraints for moving parts such as drawers and doors."],
  ["多平台兼容", "Multi-platform compatibility"],
  ["建立面向 Gazebo、UE、Isaac Sim 等平台的数据转换通道，保证数据转换的完整性与准确性。", "Build data conversion channels for Gazebo, UE, Isaac Sim and other platforms, preserving data completeness and accuracy."],
  ["仿真服务能力", "Simulation services"],
  ["交互模型", "Interaction models"],
  ["围绕机器人与场景、物体和活动部件的交互关系，组织可验证的行为与物理反馈数据。", "Organize verifiable behavior and physical-feedback data around robot interactions with scenes, objects and moving parts."],
  ["多平台支持", "Multi-platform support"],
  ["通过统一的数据工作流输出适配不同仿真平台的环境、模型和材质资源。", "Use a unified data workflow to output environments, models and materials for different simulation platforms."],
  ["快速验证", "Rapid validation"],
  ["在真实设备投入前完成环境、动作和交互策略验证，缩短研发周期并降低试错风险。", "Validate environments, actions and interaction strategies before deploying real devices, shortening development cycles and reducing trial-and-error risk."],

  ["让客户在数字空间里直接感受产品。", "Let customers experience products directly in digital space."],
  ["利用 3D 数据资源库与高逼真环境展示能力，把产品放入可理解、可体验、可传播的虚拟场景。", "Use 3D data libraries and high-fidelity environments to place products in virtual scenes that are easy to understand, experience and share."],
  ["数字化展示的三个难题", "Three challenges in digital product presentation"],
  ["产品体验不直观", "Product experience is not intuitive"],
  ["面向消费者的产品需要被放入用户熟悉的生活环境，才能让价值和变化被直接感知。", "Consumer products need to be placed in familiar living environments so their value and changes can be directly understood."],
  ["数据资源不足", "Insufficient data resources"],
  ["数字营销需要户型数据、空间布局与模型资源，快速生成用户家庭场景是基础能力。", "Digital marketing needs floor-plan data, spatial layouts and model resources; rapidly generating home scenes is a foundational capability."],
  ["技术链路复杂", "Complex technical pipeline"],
  ["户型处理、模型构建和最终展示之间存在较高技术门槛，影响营销工具的落地速度。", "The technical barriers between floor-plan processing, model construction and final presentation slow the deployment of marketing tools."],
  ["让场景成为产品的第二个展厅", "Make the scene a second showroom for the product"],
  ["海量室内户型资源", "A large library of indoor floor plans"],
  ["积累大量户型数据，用户可以快速搜索与匹配自己的空间，形成点对点的直观体验。", "Build a large floor-plan library so users can quickly search and match their own spaces for a direct, personalized experience."],
  ["多类型室内模型", "Diverse indoor models"],
  ["覆盖家具、家电、生活用品、厨卫设备等多种模型，满足不同产品的组合展示需求。", "Cover furniture, appliances, household goods, kitchen and bathroom equipment, and other models for varied product combinations."],
  ["完整技术支持", "Complete technical support"],
  ["提供 AI 场景生成、一键生成户型与风格，以及局部模型定制等能力，支持企业营销工具构建。", "Provide AI scene generation, one-click floor-plan and style generation, and partial model customization to support enterprise marketing tools."],
  ["产品展示能力", "Product presentation capabilities"],
  ["空间匹配", "Space matching"],
  ["从真实户型和生活场景出发，让产品快速进入用户自己的空间语境。", "Start from real floor plans and living scenes so products quickly enter the user's own spatial context."],
  ["模型组合", "Model composition"],
  ["通过统一资源库组织产品、材质和环境资产，形成适合传播的可视化组合。", "Organize products, materials and environment assets in one library to create visual combinations ready for communication."],
  ["虚拟体验", "Virtual experience"],
  ["以高逼真场景承载产品展示，让用户在数字空间中体验产品魅力。", "Use high-fidelity scenes to present products and let users experience their appeal in digital space."],

  ["用数据推动 XR 体验向真实世界靠近。", "Use data to bring XR experiences closer to the real world."],
  ["通过高质量空间、模型、点云和交互数据，提升 AR、VR、MR 系统的环境适应能力与用户体验。", "Use high-quality spatial, model, point-cloud and interaction data to improve environmental adaptability and user experience across AR, VR and MR systems."],
  ["XR 数据落地的四个难点", "Four challenges in deploying XR data"],
  ["数据采集困难", "Difficult data acquisition"],
  ["高质量 XR 内容需要空间数据、环境交互数据和人体动作数据，采集技术复杂且硬件成本高。", "High-quality XR content needs spatial, environmental-interaction and human-motion data, while capture technology is complex and hardware is expensive."],
  ["标注复杂度高", "High annotation complexity"],
  ["空间、场景、物体和行为都需要精确标注，点云、模型与人体关键点标注需要专业能力。", "Spaces, scenes, objects and behaviors all require precise annotation; point clouds, models and human keypoints require specialized expertise."],
  ["数据规模与多样性不足", "Insufficient data scale and diversity"],
  ["公开可用且丰富多样的 XR 数据集较少，难以满足大数据驱动技术的训练需求。", "Few rich and diverse XR datasets are publicly available, making it difficult to meet the training needs of data-driven technologies."],
  ["用户隐私保护", "User privacy protection"],
  ["需要在保证体验的同时保护 XR 环境中产生的用户数据，避免数据泄露和滥用。", "Protect user data generated in XR environments while preserving the experience and avoiding leakage or misuse."],
  ["从数据交付到内容创新", "From data delivery to content innovation"],
  ["定制化数据交付", "Custom data delivery"],
  ["整合数据采集、清洗和标注服务，直接交付可使用的数据产品，降低复杂处理成本。", "Combine capture, cleaning and annotation services to deliver usable data products directly and reduce complex processing costs."],
  ["多样数据资源", "Diverse data resources"],
  ["覆盖 3D 模型、3D 点云与环境交互数据，为 XR 内容生成和设备训练提供数据支撑。", "Cover 3D models, 3D point clouds and environmental interaction data to support XR content generation and device training."],
  ["通过数据源合规审查，生成过程不接触真实敏感数据，保障数据使用者的合规要求。", "Review data sources for compliance and avoid real sensitive data during generation to meet users' compliance requirements."],
  ["XR 数据能力", "XR data capabilities"],
  ["空间资产", "Spatial assets"],
  ["提供可复用的 3D 模型、材质、点云与环境资产，支撑内容快速搭建。", "Provide reusable 3D models, materials, point clouds and environment assets for rapid content assembly."],
  ["交互数据", "Interaction data"],
  ["围绕环境、物体与人体动作组织交互信息，让虚实融合更自然、更可验证。", "Organize interaction information around environments, objects and human motion to make mixed reality more natural and verifiable."],
  ["内容创新", "Content innovation"],
  ["让内容创作者获得稳定的数据资源，推动 XR 内容生产与应用规模化。", "Give creators dependable data resources to scale XR content production and applications."],

  ["基于群核丰富的数据库资源，我们通过技术能力驱动的数据产品，满足 AIGC、计算机视觉与机器人等行业的数据需求。", "Using Coohom's rich database resources, we build technology-driven data products for AIGC, computer vision, robotics and related industries."],
  ["通过专用数据引擎，将海量数据库转换为适配不同应用平台的 3D 模型、3D 环境与衍生图像数据。", "A dedicated data engine converts massive databases into 3D models, 3D environments and derived image data for different application platforms."],
  ["预留图片 / 视频字段", "Image / video field reserved"],
  ["继续探索群核的数据基础设施", "Explore SpatialVerse data infrastructure"],

  ["这里汇聚群核空间智能团队在合成数据、AIGC、智能体与室内场景理解方向的研究成果。", "Research from the SpatialVerse team across synthetic data, AIGC, agents and indoor scene understanding."],
  ["从空间数据到智能系统", "From spatial data to intelligent systems"],
  ["从单张图像联合恢复几何结构、空间变化光照与外观信息。", "Jointly recover geometry, spatially varying illumination and appearance from a single image."],
  ["面向室内场景修改与 2D 图像合成的可编程虚拟合成系统。", "A programmable virtual synthesis system for indoor scene editing and 2D image generation."],
  ["通过交互式帧推荐，提升复杂视频对象分割的标注效率。", "Improve annotation efficiency for complex video object segmentation with interactive frame recommendation."],
  ["面向结构化 3D 建模的大规模高真实感室内合成数据集。", "A large-scale, high-fidelity indoor synthetic dataset for structured 3D modeling."],
  ["探索语言条件下的户型生成与室内纹理合成。", "Explore language-conditioned floor-plan generation and indoor texture synthesis."],

  ["家电模型", "Appliance Models"],
  ["适用于物体识别与室内场景理解的基础模型。", "A foundational model collection for object recognition and indoor scene understanding."],
  ["基础信息", "General"],
  ["材质", "Materials"],
  ["专业家电模型", "Professional Appliance Models"],
  ["提供组件结构与标准命名的高规格家电模型。", "High-spec appliance models with component structures and standardized naming."],
  ["组件结构", "Component Structure"],
  ["标准命名", "Standard Naming"],
  ["家具模型", "Furniture Models"],
  ["覆盖室内常见家具的可复用三维模型资源。", "Reusable 3D models for common indoor furniture."],
  ["专业家具模型", "Professional Furniture Models"],
  ["带有完整结构信息的专业级家具数据。", "Professional furniture data with complete structural information."],
  ["茶壶模型", "Teapot Model"],
  ["小型物体识别与材质研究的示例模型。", "An example model for small-object recognition and material research."],
  ["识别", "Recognition"],
  ["衣柜模型", "Wardrobe Model"],
  ["室内物体理解与空间布局任务的模型样例。", "A model sample for indoor object understanding and spatial layout tasks."],
  ["室内", "Indoor"],
  ["布局", "Layout"],
  ["物理增强烤箱", "Physics-enhanced Oven"],
  ["带真实尺寸、结构和物理仿真信息的模型。", "A model with real-world scale, structure and physics-simulation information."],
  ["物理仿真", "Physics Simulation"],
  ["真实尺寸", "Real-world Scale"],
  ["柔性变形模型", "Flexible Deformation Model"],
  ["通过物理模拟生成更自然的柔性物体姿态。", "Generate more natural poses for flexible objects through physical simulation."],
  ["柔性变形", "Flexible Deformation"],
  ["物理模拟", "Physics Simulation"],
  ["飞溅变形模型", "Splash Deformation Model"],
  ["模拟细小物体自然散落与堆叠的姿态。", "Simulate natural scattering and stacking poses for small objects."],
  ["姿态生成", "Pose Generation"],
  ["破碎变形模型", "Fractured Deformation Model"],
  ["模拟完整物体受力后的自然破碎效果。", "Simulate natural fracture after a complete object is subjected to force."],
  ["破碎模拟", "Fracture Simulation"],
  ["异常状态", "Anomaly States"],
  ["室内家居场景", "Indoor Home Scene"],
  ["覆盖客厅、卧室、卫生间和厨房的室内场景。", "Indoor scenes covering living rooms, bedrooms, bathrooms and kitchens."],
  ["语义标注", "Semantic Annotation"],
  ["实例分割", "Instance Segmentation"],
  ["商业空间场景", "Commercial Space Scene"],
  ["面向餐厅、厨房、用餐区和吧台的商业空间数据。", "Commercial-space data for restaurants, kitchens, dining areas and bars."],
  ["商业空间", "Commercial Space"],
  ["仿真", "Simulation"],
  ["物体识别数据集", "Object Recognition Dataset"],
  ["将不同产品放入不同场景中进行识别。", "Recognize different products placed in different scenes."],
  ["物体识别", "Object Recognition"],
  ["多场景", "Multi-scene"],
  ["室内弓形轨迹合成数据集", "Indoor Bow-trajectory Synthetic Dataset"],
  ["模拟扫地机器人清扫时的室内轨迹数据。", "Simulate indoor trajectory data generated by a robot vacuum during cleaning."],
  ["轨迹", "Trajectory"],
  ["机器人", "Robotics"],
  ["室内随机漫游合成数据集", "Indoor Random-roaming Synthetic Dataset"],
  ["模拟人在室内行走视角下的多通道图像数据。", "Simulate multi-channel image data from a person's walking perspective indoors."],
  ["随机轨迹", "Random Trajectory"],
  ["室内视觉", "Indoor Vision"],

  ["群核科技旗下的 Koolab 创新实验室借助酷家乐全球规模化的 3D 室内设计平台，自 2018 年起专注于 3D 场景虚拟合成技术研发。我们与国内外高校和科研机构展开合作，为群核空间智能平台提供可靠的技术支持。", "Koolab, the innovation lab of Coohom, has used Coohom's globally scaled 3D interior design platform to focus on virtual 3D scene synthesis since 2018. We collaborate with universities and research institutions worldwide to provide reliable technical support for SpatialVerse."],
  ["机器人", "Robotics"],
  ["室内智能体", "Embodied Indoor Agents"],
  ["杰出的数据质量和专业精神！我们的虚拟研究建筑现在拥有大量且多模态的逼真的物体模型，推进了服务机器人领域的发展。", "Outstanding data quality and professionalism. Our virtual research building now contains a large collection of realistic, multimodal object models that advance service robotics."],
  ["“杰出的数据质量和专业精神！我们的虚拟研究建筑现在拥有大量且多模态的逼真的物体模型，推进了服务机器人领域的发展。”", "“Outstanding data quality and professionalism. Our virtual research building now contains a large collection of realistic, multimodal object models that advance service robotics.”"],
  ["不莱梅大学", "University of Bremen"],

  ["返回顶部 ↑", "Back to Top ↑"],
  ["AIGC技术爆发的时代，诞生了多种生成式大模型，通常这些模型是基于大量数据进行预训练，群核空间智能平台可以提供包括图像，视频，模型等多种要素的训练数据资源，并具备完整的标签体系，帮助AIGC研究者实现大模型技术突破。", "As generative models proliferate, SpatialVerse provides training resources across images, video and models with complete label systems, helping AIGC researchers advance foundation-model technology."],
  ["机器人仿真可以快速，低成本，安全的对产品进行验证，群核空间智能平台通过提供高渲染和物理真实性的仿真环境，并结合具体仿真平台打造仿真环境数据库，为企业机器人仿真提供助力。", "Robot simulation enables fast, low-cost and safe product validation. SpatialVerse provides high-fidelity, physically realistic environments and simulation databases for enterprise robotics workflows."],
  ["数字化展示是一种可以让客户直观感受产品魅力的手段，群核空间智能平台通过3D数据资源库以及高逼真的环境展示能力，通过数据赋能，让用户在虚拟环境中感受产品魅力。", "Digital presentation lets customers experience a product's appeal directly. SpatialVerse combines 3D data libraries with high-fidelity environments to bring products to life in virtual spaces."],
  ["高质量数据集能显著提升AR/VR/MR系统的环境适应能力和用户体验，如精确的虚实结合效果、顺畅的交互操作等。同时，数据集也赋能内容创作者获取必要的3D模型、材质和动画资源，推动内容创新，从而有力推进XR技术的整体进步与广泛应用。", "High-quality datasets improve environmental adaptability and user experience across AR, VR and MR, while giving creators the 3D models, materials and animation resources needed to advance XR content and applications."],
  ["图片、视频与多模态训练资源", "Images, video and multimodal training resources"],
  ["可复用的3D模型与材质资源", "Reusable 3D models and materials"],
  ["高渲染与物理真实性的3D场景", "High-fidelity, physically realistic 3D scenes"],
];
