services:
  - type: web
    name: spatial-verse-cms
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: APOS_DB_URI
        sync: false
      - key: APOS_EXTERNAL_FRONT_KEY
        sync: false
      - key: NODE_VERSION
        value: "22"
